Fix optional scope not respected when using --scopes flag
compilerla/conventional-pre-commit pull request #113
Opened 2024-09-27 17:34 UTC by nimaps

Fixes issue #111 where the optional flag in the r_scope function was ignored when custom scopes were provided, making the scope mandatory even when optional=True.

2024-10-02 11:52 UTC, thekaveman requested changes
The code changes look great, thank you!

I see that you added the `optional=False` to one of the existing tests, which is good. May I request some additional test(s), specifically for this use-case / error?

Take a look at the tests in [`test_hook.py`](https://github.com/compilerla/conventional-pre-commit/blob/main/tests/test_hook.py) that are focused on either calling the `main` function or using a subprocess to call the CLI itself. Would you mind adding a few tests here that demonstrate e.g. the POC you originally gave in https://github.com/compilerla/conventional-pre-commit/issues/111#issue-2540515243

2024-10-02 12:25 UTC, nimaps commented
@thekaveman absolutely! I'll update the PR asap.

2024-10-14 19:03 UTC, mjspeck commented
Any movement on this? Would love to incorporate scopes into my `pre-commit` workflow.

2024-10-15 10:11 UTC, nimaps commented
@thekaveman I included the tests for possible combination of states. Would you please take a look?

Thank you.

2024-10-15 15:56 UTC, thekaveman approved these changes
Fantastic, thank you @nimaps for the extra tests!

2024-10-15 15:56 UTC, merged

2024-10-15 19:50 UTC, thekaveman commented
Thanks again @nimaps! cc @mjspeck 

This fix is now [released in `3.5.0`](https://pypi.org/project/conventional-pre-commit/3.5.0/)